print("Welcome to the tip calculator!")
bill = float(input("What was the total bill? $"))
tip = int(input("What percentage tip would you like to give? 10 12 15 "))
people = int(input("How many people to split the bill? "))

tip_per = float((tip/100) * bill)
all_price = float(bill + tip_per)
bill_per_person = float(all_price/people)
final_amount = round(bill_per_person, 2)
print(f"Each person should pay : {final_amount}")
